
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: OOIDetectorInput.proto
namespace Magic.OOIDetector
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OOIDetectorInput")]
    public partial class OOIDetectorInput : global::ProtoBuf.IExtensible
    {
      public OOIDetectorInput() {}
      
    private Magic.OOIDetector.OOIDetectorInput.Robotpose _pose;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pose", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Magic.OOIDetector.OOIDetectorInput.Robotpose pose
    {
      get { return _pose; }
      set { _pose = value; }
    }
    private readonly global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorInput.Point> _points = new global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorInput.Point>();
    [global::ProtoBuf.ProtoMember(2, Name=@"points", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorInput.Point> points
    {
      get { return _points; }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Robotpose")]
    public partial class Robotpose : global::ProtoBuf.IExtensible
    {
      public Robotpose() {}
      
    private double _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double x
    {
      get { return _x; }
      set { _x = value; }
    }
    private double _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double y
    {
      get { return _y; }
      set { _y = value; }
    }
    private double _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double z
    {
      get { return _z; }
      set { _z = value; }
    }
    private double _roll;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double roll
    {
      get { return _roll; }
      set { _roll = value; }
    }
    private double _pitch;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private double _yaw;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private double _timestamp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private readonly global::System.Collections.Generic.List<double> _covariance = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(8, Name=@"covariance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> covariance
    {
      get { return _covariance; }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ThreeDCoord")]
    public partial class ThreeDCoord : global::ProtoBuf.IExtensible
    {
      public ThreeDCoord() {}
      
    private double _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double x
    {
      get { return _x; }
      set { _x = value; }
    }
    private double _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double y
    {
      get { return _y; }
      set { _y = value; }
    }
    private double _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double z
    {
      get { return _z; }
      set { _z = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Point")]
    public partial class Point : global::ProtoBuf.IExtensible
    {
      public Point() {}
      
    private Magic.OOIDetector.OOIDetectorInput.ThreeDCoord _globalcoord;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"globalcoord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Magic.OOIDetector.OOIDetectorInput.ThreeDCoord globalcoord
    {
      get { return _globalcoord; }
      set { _globalcoord = value; }
    }
    private Magic.OOIDetector.OOIDetectorInput.ThreeDCoord _robotcoord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"robotcoord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Magic.OOIDetector.OOIDetectorInput.ThreeDCoord robotcoord
    {
      get { return _robotcoord; }
      set { _robotcoord = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}