
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: pose.proto
namespace Magic.Proto
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pose")]
    public partial class Pose : global::ProtoBuf.IExtensible
    {
      public Pose() {}
      
    private double _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double x
    {
      get { return _x; }
      set { _x = value; }
    }
    private double _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double y
    {
      get { return _y; }
      set { _y = value; }
    }
    private double _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double z
    {
      get { return _z; }
      set { _z = value; }
    }
    private double _yaw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private double _pitch;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private double _roll;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double roll
    {
      get { return _roll; }
      set { _roll = value; }
    }
    private double _timeStamp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}