
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: OOIDetectorTarget.proto
namespace Magic.OOIDetector
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OOIDetectorTarget")]
    public partial class OOIDetectorTarget : global::ProtoBuf.IExtensible
    {
      public OOIDetectorTarget() {}
      
    private readonly global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.Blob> _oois = new global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.Blob>();
    [global::ProtoBuf.ProtoMember(1, Name=@"oois", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.Blob> oois
    {
      get { return _oois; }
    }
  
    private double _timeStamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Point")]
    public partial class Point : global::ProtoBuf.IExtensible
    {
      public Point() {}
      
    private double _u;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"u", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double u
    {
      get { return _u; }
      set { _u = value; }
    }
    private double _v;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"v", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double v
    {
      get { return _v; }
      set { _v = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BBox")]
    public partial class BBox : global::ProtoBuf.IExtensible
    {
      public BBox() {}
      
    private int _tlx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tlx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tlx
    {
      get { return _tlx; }
      set { _tlx = value; }
    }
    private int _tly;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tly
    {
      get { return _tly; }
      set { _tly = value; }
    }
    private int _brx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"brx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int brx
    {
      get { return _brx; }
      set { _brx = value; }
    }
    private int _bry;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bry
    {
      get { return _bry; }
      set { _bry = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MiddlePoint")]
    public partial class MiddlePoint : global::ProtoBuf.IExtensible
    {
      public MiddlePoint() {}
      
    private int _R;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"R", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int R
    {
      get { return _R; }
      set { _R = value; }
    }
    private int _uPix;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uPix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uPix
    {
      get { return _uPix; }
      set { _uPix = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Blob")]
    public partial class Blob : global::ProtoBuf.IExtensible
    {
      public Blob() {}
      
    private Magic.OOIDetector.OOIDetectorTarget.Point _center;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Magic.OOIDetector.OOIDetectorTarget.Point center
    {
      get { return _center; }
      set { _center = value; }
    }
    private Magic.OOIDetector.OOIDetectorTarget.BBox _bound;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Magic.OOIDetector.OOIDetectorTarget.BBox bound
    {
      get { return _bound; }
      set { _bound = value; }
    }

    private string _ooitype = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ooitype", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string ooitype
    {
      get { return _ooitype; }
      set { _ooitype = value; }
    }
    private readonly global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.MiddlePoint> _middlePoints = new global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.MiddlePoint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"middlePoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Magic.OOIDetector.OOIDetectorTarget.MiddlePoint> middlePoints
    {
      get { return _middlePoints; }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}